# Generated by Django 4.0.3 on 2022-04-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_ids',
            new_name='category_id',
        ),
    ]
